[package]
name = "clock"
version = "0.1.0"
edition = "2021"

[lib]
name = "clock"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.43"
lazy_static = "1.5.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
ctrlc = "3.4"
